import {
  Moon,
  SunMedium,
  Wallet,
  User,
  ShoppingCart,
  Users,
  QrCode,
  Plus,
  Minus,
  Save,
  NotebookTabs,
  Smile,
  CreditCard,
  Calendar,
  Package,
  LogOut,
  Mail,
  Layers,
  Settings,
  LayoutGrid,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  ChevronDown,
  Eye,
  MoreHorizontal,
  ArrowUpDown,
  ArrowLeft,
  ArrowRight,
  Check,
  Search,
  Circle,
  GripVertical,
  Phone,
  MapPin,
  Truck,
  Handshake,
  BookText,
  Trash2
} from "lucide-react"


const Icons = {
  trash: Trash2,
  book: BookText,
  truck: Truck,
  mapPin: MapPin,
  phone: Phone,
  chevL: ChevronLeft,
  chevR: ChevronRight,
  chevL2: ChevronsLeft,
  chevR2: ChevronsRight,
  chevU: ChevronUp,
  chevD: ChevronDown,
  eye: Eye,
  more: MoreHorizontal,
  arrowUD: ArrowUpDown,
  arrowL: ArrowLeft,
  arrowR: ArrowRight,
  check: Check,
  search: Search,
  circle: Circle,
  grip: GripVertical,
  mail: Mail,
  calendar: Calendar,
  creditcard: CreditCard,
  smile: Smile,
  notebook: NotebookTabs,
  save: Save,
  plus: Plus,
  minus: Minus,
  sun: SunMedium,
  moon: Moon,
  qrcode: QrCode,
  logout: LogOut,
  dashboard: LayoutGrid,
  package: Package,
  stack: Layers,
  wallet: Wallet,
  users: Users,
  user: User,
  settings: Settings,
  cross: X,
  cart: ShoppingCart,
  handshake: Handshake,
}

export default Icons